name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: singhdivyanshdishu
          outputs: |
            dist/github-snake.svg?color_snake=%2388C0D0&color_dots=%232E3440,%233B4252,%23434C5E,%234C566A,%2381A1C1
            dist/github-snake-dark.svg?color_snake=%2388C0D0&color_dots=%232E3440,%233B4252,%23434C5E,%234C566A,%2381A1C1

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
